240308_24_장날아
orm-camp-flutter-2ki/learn_dart_together pull request #43
Opened 2024-03-08 06:19 UTC by NalaJang

## 연습 문제 1
**Cleric클래스에 관하여, 2가지 수정을 하시오**  
현시점의 Cleric 클래스의 정의에는, 각 인스턴스별로 최대 HP와 최대 MP 필드에 대한 정보를 가지고 있다. 
하지만, 모든 성직자의 최대 HP 는 50, 최대 MP 는 10으로 정해져 있어, 각 인스턴스가 각각의 정보를 가지는 것은 메모리 낭비이다. 
그래서, 최대 HP, 최대 MP의 필드가 공유 되도록 필드 선언에 적절한 키워드를 추가하시오.

## 연습 문제 2
**아래의 방침에 따라, 생성자를 추가 하시오**
A) 이 클래스는 Cleric(“아서스", hp: 40, mp: 5) 와 같이, 이름, HP, MP 를 지정하여 인스턴스화 할 수 있다.
B) 이 클래스는 Cleric(“아서스", hp: 35) 와 같이, 이름과 HP만으로 지정하여 인스턴스화 할 수 있다. 
이 때, MP는 최대 MP와 같은 값이 초기화 된다.
C) 이 클래스는 Cleric(“아서스") 와 같이 이름만을 지정하여 인스턴스화 할 수 있다. 이 때, HP 와 MP 는 최대 HP와 최대 MP로 초기화 된다.
D) 이 클래스는 Cleric() 과 같이 이름을 지정하지 않는 경우에는 인스턴스화 할 수 없다고 한다. (이름이 없는 성직자는 존재 할 수 없음)
E) 생성자는 가능한 한 중복되는 코드가 없도록 작성한다.

2024-03-08 07:15 UTC, junsuk5 requested changes

2024-03-08 07:15 UTC, junsuk5 commented on lib/240308/cleric.dart
> +  Cleric({required this.name, this.hp = Cleric.maxHp, this.mp = Cleric.maxMp});
요구사항에 name 은 named parameter 가 아니니 수정이 필요해 보입니다

2024-03-08 07:21 UTC, NalaJang commented on lib/240308/cleric.dart
> +  Cleric({required this.name, this.hp = Cleric.maxHp, this.mp = Cleric.maxMp});
넵. 수정했습니다.

2024-03-08 11:28 UTC, junsuk5 approved these changes
수정 사항 확인하였습니다

2024-03-08 11:28 UTC, merged

2024-03-08 11:31 UTC, junsuk5 commented
그런데 일부러 수업 내용 코드를 땡겨가는 것인가요? 제 커밋이 섞여있는 것 같아서요.

2024-03-10 03:30 UTC, NalaJang commented
> 그런데 일부러 수업 내용 코드를 땡겨가는 것인가요? 제 커밋이 섞여있는 것 같아서요.

아. 결석한 사이에 생긴 첫 코드 과제라서, 급하게 몽땅 들고 왔었습니다 😅