240308_11_서현웅
orm-camp-flutter-2ki/learn_dart_together pull request #44
Opened 2024-03-08 06:24 UTC by iOS-Woong

- Cleric 수정

2024-03-08 07:45 UTC, intelliM requested changes

2024-03-08 07:45 UTC, intelliM commented on lib/240308/cleric.dart
> +  Cleric(this.name, {this.hp = 50, this.mp = 10});
maximumHp, maximumMp 를 활용 할 수 있는 방법을 생각해 보세요.

2024-03-09 13:27 UTC, iOS-Woong commented on lib/240308/cleric.dart
> +  Cleric(this.name, {this.hp = 50, this.mp = 10});
# 1. 생성자 내부에서 정적프로퍼티를 사용하지 못한 이유

```dart
static final int maximumHp = 50;
static final int maximumMp = 10;

Cleric(this.name, {this.hp = Cleric.maximumHP, this.mp = Cleric.maximumMP});
```
1. 제 코드의 생섬함수는 매직넘버를 사용해서 구현되어 있었습니다.
2. 이유는 최초에 제가 정적 프로퍼티를 활용하여 값을 채워주려 시도하였으나,
3. 에러가 발생하여 "이건 안되나보다"라고 하고 빠르게 넘어간 개념이였습니다. (잘못한점)

# 2. 에러를 살펴보게됨
```dart
1. Error: Member not found: 'maximumHP'. // maximumHP라는 멤버를 찾을 수 없음.

2. Context: The invocation of 'maximumMp' is not allowed in a constant expression.0
// 상수 표현(constant expression)에서 'maximumMp'를 호출하는 것은 허용되지 않습니다.
```

1. 왜 찾을 수 없다고 하는거지? 난 분명히 위에서 선언했는데 생각하였는데...

# 3. 해결
```dart
Cleric secondCleric = Cleric("아서스", hp: 20, mp: 3);

static const int maximumHP = 10;
static const int maximumMP = 10;
```
1. 정답은 const(컴파일시점)와 final(런타임시점) 키워드로 선언한 변수들이 메모리에 올라가는 시점에 있었습니다.
2. 제 코드는 두 정적변수를 final로 선언해두었습니다.
3. 따라서, 제가 Cleric이라는 인스턴스를 생성하는 시점에는 `Class.maximumHP`가 아직 메모리에 올라가있지 않은 상태였습니다.
4. 즉, 해당 정적변수에 값이 할당되지 않은 시점에 `Class.maximumHP` 라는 정적변수를 호출하였으므로 에러가 발생하는 것이였습니다.
5. 따라서, 위와 같이 const를 사용해주면 컴파일시점에 변수를 미리 메모리에 올려두므로 Cleric의 생성자로 Cleric을 사용 할 수 있게 되었습니다!


---
@intelliM 
혹시 제가 도출해 낸 결론이 맞는건가요 ? ? ?
틀린점이 있다면 코멘트 남겨주시면 감사하게씀당

주말인데 좋은 코멘트 남겨주셔서 감사합니다 ~~

2024-03-10 04:15 UTC, junsuk5 commented on lib/240308/cleric.dart
> +  Cleric(this.name, {this.hp = 50, this.mp = 10});
네. 맞습니다.
어설프게 알고 있던 final 과 const 를 잘 정리해 볼 수 있는 문제였습니다. 👍

그리고 50, 10 대신 Class.maximumHP 와 Class.maximunMP 를 사용하라고 한 것은 또 다른 이유가 있기 때문입니다.
흔히 매직 넘버를 사용하는 것은 좋지 않으니(왜?) 상수를 사용하라는 말이 있습니다.
이런 것들도 추가로 생각해 보시면 좋을 것 같습니다.

2024-03-11 04:57 UTC, merged