240308_18_양혜영
orm-camp-flutter-2ki/learn_dart_together pull request #54
Opened 2024-03-08 07:14 UTC by dmm-asmong

성직자 인스턴스 필드수정 및 생성자 추가

- Cleric 필드 공유 static 추가
- Cleric 클래스 생성자 네임드 파라미터 변경

2024-03-08 07:17 UTC, junsuk5 requested changes
전반적으로 컨벤션이 잘 반영되었네요
클래릭 생성자만 수정이 필요해 보입니다

2024-03-08 07:17 UTC, junsuk5 commented on lib/240307/cleric.dart
> +  Cleric({required this.name, this.hp = maxhp, this.mp = maxmp});
이름 부분은 요구사항에 named parameter 가 아니니 확인해서 수정하시면 될 것 같습니다

2024-03-08 07:41 UTC, dmm-asmong commented on lib/240307/cleric.dart
> +  Cleric({required this.name, this.hp = maxhp, this.mp = maxmp});
넵 수정했습니다!

2024-03-09 05:06 UTC, junsuk5 approved these changes
수정 사항 확인했습니다. 수고하셨습니다.

2024-03-09 05:06 UTC, merged