240308_21_이서우
orm-camp-flutter-2ki/learn_dart_together pull request #55
Opened 2024-03-08 07:30 UTC by leeseowoo

## 작업 내용
### 공유 자원 static으로 변경
- 모든 Cleric 인스턴스가 사용하는 공유 필드를 top level(static)로 이동하여, 인스턴스를 생성할 때마다 동일한 필드가 불필요하게 메모리를 점유하지 않도록 변경했습니다.

### 생성자 변경
- 생성자의 소괄호 안에 중괄호를 사용하여 네임드 파라미터를 사용할 수 있도록 했습니다.
- name 매개변수 앞에 required 키워드를 사용하여 필수로 값이 전달되도록 했습니다.
- 값이 전달되지 않을 수 있는 hp, mp 매개변수는 default로 maxHp, maxMp 값을 갖도록 maxHp, maxMp에 final 대신 const를 사용하여 컴파일 타임 상수로 변경했습니다. null이 아닌 값으로 default 값을 정하기 위해서는 컴파일 타임 상수의 이름 또는 값 자체를 지정해야 합니다.

2024-03-08 07:48 UTC, junsuk5 requested changes
PR 내용 너무 좋네요
클레릭 생성자만 수정 필요해 보입니다

2024-03-08 07:48 UTC, junsuk5 commented on lib/0307/cleric.dart
> +  Cleric({required this.name, this.hp = maxHp, this.mp = maxMp}) {
문제를 잘 보시고 요구사항에 맞게 name 쪽 수정이 필요해 보입니다

2024-03-09 05:09 UTC, junsuk5 requested changes

2024-03-09 05:09 UTC, junsuk5 commented on lib/0308/cleric.dart
> +  }
문제에서 name 은 필수 파라미터이지만 named 파라미터는 아니기 때문에 수정이 필요해 보입니다

2024-03-09 11:02 UTC, leeseowoo commented on lib/0308/cleric.dart
> +  }
수정했습니다. 감사합니다 :)

2024-03-09 11:03 UTC, junsuk5 approved these changes
확인했습니다. 수고하셨습니다

2024-03-09 11:03 UTC, merged