240308_03_김세진
orm-camp-flutter-2ki/learn_dart_together pull request #64
Opened 2024-03-08 08:41 UTC by david-s-kim

**5일차 연습문제**

>연습문제 1번, 2번

- 4일차 연습문제의 Cleric 클래스에 생성자조건을 추가
- Named Parameter를 추가하여 순서에 상관없이 매핑

2024-03-09 05:22 UTC, junsuk5 requested changes
코멘트 확인해서 수정 바랍니다

2024-03-09 05:22 UTC, junsuk5 commented on lib/24_03_07/cleric.dart
> +  Cleric({required this.name, this.hp = 40, this.mp = 5});
문제를 잘 보면 name 은 필수이지 named 는 아닙니다

2024-03-09 05:22 UTC, junsuk5 commented on lib/24_03_08/constructor.dart
> +void main(){
코드 정리

2024-03-09 05:22 UTC, junsuk5 commented on lib/24_03_08/00_memory.dart
> +void main(){
코드 정리

2024-03-10 11:45 UTC, david-s-kim commented
수정했습니다~ 감사합니다!

2024-03-10 11:46 UTC, junsuk5 commented on lib/24_03_07/cleric.dart
> +  Cleric({required this.name, this.hp = 40, this.mp = 5});
이 부분도 주요 수정 포인트입니다

2024-03-11 04:58 UTC, merged